---
title: Conference Proceedings (Peer Reviewed)
author: 'N Korf'
date: "`r format(Sys.time(), '%Y-%m-%d')`"
slug: publications-conferences
categories: []
tags: []
---

<ol reversed>

<li><p>Karatzas, A., Stamolampros, P., Daskalakis, G., and  Korfiatis, N. (2017). 
The effect of manufacturers’ service transition
on employee job satisfaction. In <em>Proceedings of the 25th International EurOMA Conference 2018 </em>(D4). Budapest, Hungary.</p></li>  

<li><p>Huang, G-H., Korfiatis, N. (2017). 
To Abandon or Not to Abandon a Mobile Shopping Cart: The Role of Ambivalence. In <em>Proceedings of the  American Marketing Association Winter Educators Conference 2017</em>(D4). Orlando, Florida, United States of America.</p></li>

<li><p>Mertz, M., Korfiatis, N., Zicari, R. V. (2014). Using Dependency Bigrams and Discourse Connectives for Predicting the Helpfulness of Online Reviews. In <em>E-Commerce and Web Technologies </em>(pp. 146-152). <em>Proceedings of EC-Web 2014, in conjunction with the DEXA Workshop.</em> Lecture Notes in Business Information Processing, Springer.</p></li>

<li><p>Korfiatis, N. (2013). Big Data for Enhancing Learning Analytics: A Case for Large-Scale Comparative Assessments. <em>Proceedings of the 7th International Conference on Metadata and Semantics Research</em>. Springer Series in Communications in Computer and Information Science. Vol 390. Thessaloniki, Greece.</p></li>

<li><p>Niemann, R., Korfiatis, N., Zicari, R. V., Göbel, R. (2013). Evaluating the energy efficiency of OLTP operations. <em>Paper presented at the Availability, Reliability, and Security in Information Systems and HCI</em> / Lecture Notes in Computer Science Volume 8127, 2013, pp 28-43, Regensburg, Germany.</p></li>

<li><p>Korfiatis, N., Loebbecke, C., Cremer, S. (2012) Successfully Bidding for Online Projects: The Impact of Project-Focused Messages. <em>International Workshop on e-Business (WEB 2012), Pre-ICIS Workshop sponsored by AIS SIGeBIZ, Theme:Cloud Computing and Analytics: Innovations in E-Business Services</em>, Orlando, Florida, USA.</p></li>

<li><p>Rill, S., Adolph, S., Drescher, J., Reinel, D., Scheidt, J., Schutz, O., Wogenstein, F., Korfiatis, N, Zicari, R.V. (2012). A phrase-based opinion list for the German language. <em>In J. Jancsary (Ed.), Proceedings of the11th Conference on Natural Language Processing (KONVENS 2012)</em>, pp. 305–313. Vienna, Austria</p></li>

<li><p>Wu, P. F., Heijden, H. V. D., &amp; Korfiatis, N. (2011). The Influences of Negativity and Review Quality on the Helpfulness of Online Reviews. <em>Proceedings of the International Conference on Information Systems (ICIS), 2011</em>. Shanghai, China.</p></li>

<li><p>Poulos M., Korfiatis N. (2010). Development of Diagnosis Aiding Ontology based on Hysteroscopy Image Processing. <em>Proceedings of the 4th International Conference on Metadata and Semantics Research</em>. Springer Series in Communications in Computer and Information Science. Alcala de Henares, Spain.</p></li>

<li><p>Barriocanal-Garcia, E., Sicilia, M.A, Korfiatis, N (2010). Exploring hotel service quality experience indicators in user-generated content: A case using Tripadvisor data. <em>Proceedings of the 2010 Mediterranean Conference on Information Systems (MCIS)</em>. Tel-Aviv. Israel.</p></li>

<li><p>Korfiatis N., Rodriguez D., Sicilia M.A. (2008). The impact of Readability on the Usefulness of Online Product Reviews: A Case Study on an Online Bookstore. <em>Proceedings of WSKS 2008, pp 423-432</em>. Lecture Notes in Computer Science Vol.5288 Springer, Berlin/Heidelberg.</p></li>

<li><p>Sicilia M.A., Barriocanal-Garcia, E., Korfiatis N. (2008). Using Imperfect Information in Online Social Systems: Applications and Measures of Betweeness. <em>Proceedings of the 12th International Conference on Information Processing and Management of Uncertainty (IPMU 2008)</em>. Malaga, Spain</p></li>

<li><p>Korfiatis, N., Sicilia, M. A. (2007). Social Measures and Flexible Navigation on Online Contact Networks. <em>In Proceedings of the IEEE International Conference on Fuzzy Systems (FUZZ-IEEE) Soft Approaches on Information Access on the Web</em> (pp. 1-6). Imperial College. London UK.</p></li>

<li><p>Korfiatis, N. (2007). Social and Economic Incentives in Online Social Interactions: A Model and Typology. <em>Proceedings of the 30th Information Systems Research Seminar in Scandinavia (IRIS)</em>, University of Tampere, Finland.</p></li>

<li><p>Poulos, M., Korfiatis, N., Bokos, G. (2007) Towards the Definition of a Global Bibliometric Indicator. in <em>Proceedings of the 11th International Conference of the International Society for Scientometrics and Informetrics (ISSI)</em>. Madrid, Spain.</p></li>

<li><p>Korfiatis, N., Poulos, M., Bokos, G. (2007). Analyzing Scientific Networks using Conflict of Interest. <em>Proceedings of Sunbelt XXVII International Conference on Social Network Analysis</em>. Corfu, Greece.</p></li>

<li><p>Korfiatis, N., Constantiou, I. (2006). Socially Targeted Mobile Services: Towards an Upper Level Ontology of Social Roles for Mobile Environments. in <em>Proceedings of the 14th European Conference of Information Systems (ECIS 2006)</em>. Gothenburg Sweden.</p></li>

<li><p>Korfiatis, N., Lytras M. (2006). Deploying recommender systems for microcontent: An approach using social network theory. In <em>Proceedings of Microlearning 2006: Micromedia and E-Learning</em>. Innsbruck, Austria.</p></li>

<li><p>Lytras, M.D., Pouloudi, A., Korfiatis, N. (2003). An Ontological Oriented Approach on E-Learning. Integrating Semantics for Adaptive E-Learning Systems. New Paradigms in Organizations, Markets and Society. <em>Proceedings of the 11th European Conference on Information Systems (ECIS 2003)</em>, Naples. Italy</p></li>
</ol>